# top level Makefile

SUBDIRS = 1_transfer 2_mempool 3_dispatch 4_radioChannels

all install clean::
	for i in $(SUBDIRS); do \
	    echo "-- Making $@ in $$i"; \
	    ( cd $$i && $(MAKE) $(MFLAGS) $@ ); \
	    echo "-- Done making $@ in $$i"; \
	done

